# Book settings
title: Human-First AI Guide
author: H1st.AI
logo: H1st-logo.png

repository:
  url                       : https://github.com/h1st-ai/h1st

html:
  favicon                   : H1st-logo.png
  use_repository_button     : true
  baseurl                   : "http://h1st.ai/"
  google_analytics_id       : "UA-40192392-7"
  extra_navbar              : >
    <div style="width: 240px; text-align: left">
      <iframe src="https://ghbtns.com/github-btn.html?user=h1st-ai&repo=h1st&type=star&count=true" frameborder="0" scrolling="0" width="100" height="20" title="GitHub"></iframe>
      <iframe src="https://ghbtns.com/github-btn.html?user=h1st-ai&repo=h1st&type=fork&count=true" frameborder="0" scrolling="0" width="100" height="20" title="GitHub"></iframe>
    </div>

execute:
  execute_notebooks         : false  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
